version: '3.8'

services:
  db:
    image: postgres:13
    container_name: bank-db
    restart: always
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: bank-service
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://bankuser:bankpass@db:5432/bankdb?sslmode=disable
    ports:
      - "8080:8080"
    restart: always

volumes:
  pgdata:
